### ISSUE TITLE
1.16-forge marked as fabric

### ISSUE THREAD

**Issue by puggan** [nanite/Bamboo-Everything#19]
This file in the forge is marked as fabric.
https://www.curseforge.com/minecraft/mc-mods/bamboo-everything-forge/files/3071140

At the page for the fabric-mod, there is no 1.16 version, and in the forge-mod, there is a file, marked as fabric, but named forge.
Very confusing.

Tested it in fabric, but got no bamboo-blocks.

**Comment by Gaz492** [comment]
fixed
