### ISSUE TITLE
Bamboo Ladders don't function as ladders

### ISSUE THREAD

**Issue by KihakuGato** [nanite/Bamboo-Everything#20]
the bamboo ladders are beautiful but it doesn't appear you can climb up/down them like you can with an actual ladder

**Comment by K0-RR** [comment]
They work for me. Fabric.

**Comment by Gaz492** [comment]
> the bamboo ladders are beautiful but it doesn't appear you can climb up/down them like you can with an actual ladder

Which modloader?

**Comment by KihakuGato** [comment]
forge modloader 1.16, it appears it's been fixed in the latest update though, thank you
