### ISSUE TITLE
[1.17.1] "Crash" / Mod loading error when loading game instance.

### ISSUE THREAD

**Issue by Gbergz** [nanite/Bamboo-Everything#29]
Using the newest release for 1.17 makes the game crash / has a mod loading error.

**Minecraft**: 1.17.1
**Forge**: 37.0.28
**Bamboo Everything**: 1.0.0 | File: https://www.curseforge.com/minecraft/mc-mods/bamboo-everything-forge/files/3422308

**Logs / Crash-Report:**
https://gist.github.com/Gbergz/e6aeaee79caebbc6e683681a53473909

**Screenshot**
![image](https://user-images.githubusercontent.com/26634554/129090248-dfe94a15-8535-4659-a3e9-fdbbbca4accf.png)

**-** Gbergz

**Comment by Gbergz** [comment]
Fixed with the newest release you released. Thank you.

**Comment by Gaz492** [comment]
No problem
