### ISSUE TITLE
Crash Upon Start

### ISSUE THREAD

**Issue by ReeCodes** [nanite/Bamboo-Everything#30]
### Mod version

1.0.0mc1.16.5

### Forge mod loader version

1.16.5 - 36.2.19

### Repeatable?

- [X] Yes

### Steps to reproduce the issue

Start MC.

### Description of the issue you are having

Crash upon start.
https://mclo.gs/y6CfR6i

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
I tried to replicate the issue you were having but I am unable to the mod launches without any issues when using the same versions you mentioned, my best guess would be to try restarting the server/client.

I will have a new build out later that's built against newer versions of forge and architecture with an update ladder model but not sure if that will fix the issue your having either.
