### ISSUE TITLE
[Feature Request] Support for 1.18(.1) Fabric

### ISSUE THREAD

**Issue by PoneyClairDeLune** [nanite/Bamboo-Everything#32]
### Feature Description

Please update the Fabric version of this mod to 1.18(.1).

**Comment by Terminal-Access** [comment]
+1 Requesting the Fabric version be updated to 1.18.2 please.

**Comment by Gaz492** [comment]
While not 1.18 I do now have a 1.19 version.
Not sure if I will back port to 1.18 at the moment
