### ISSUE TITLE
Add a different language & support for JEI-Item-Search

### ISSUE THREAD

**Issue by DancerVlt69** [nanite/Bamboo-Everything#37]
### Feature Description

Hello 
Do you have planed to add  German into the mod? If it is so, my translation should be correct and works fine in the latest versions for MC 16.5 and 18.2

`{
  "itemGroup.bambooeverything.bambooeverything": "Bamboo Everything",
  
  "block.bambooeverything.bamboo_ladder": "Bambusleiter",
  "block.bambooeverything.bamboo_fence": "Bambuszaun",
  "block.bambooeverything.bamboo_fence_gate": "Bambuszauntor",
  "block.bambooeverything.bamboo_door": "Bambustür",
  "block.bambooeverything.bamboo_trapdoor": "Bambusfalltür",
  "block.bambooeverything.bamboo_bundle": "Bambusbündel",
  "block.bambooeverything.bamboo_stairs": "Bambustreppe",
  "block.bambooeverything.bamboo_slab": "Bambusstufe",
  "item.bambooeverything.bamboo_raft": "Bambusfloß"
}`

And also I've added json-files - a complete folder 'items' - that your mod supports the JEI - Item - Search

[bambooeverything-1_2_6-b13-mc1.18.2__LangAdd&JEI-Item-Search.zip](https://github.com/nanite/Bamboo-Everything/files/8641395/bambooeverything-1_2_6-b13-mc1.18.2__LangAdd.JEI-Item-Search.zip)

![2022-05-06_15 50 25_BabooEv_changes](https://user-images.githubusercontent.com/49952690/167148807-b5ce2e08-12af-447c-aa46-97b7b290ab12.png)

Best regards

**Comment by Gaz492** [comment]
If you can open a PR with the changes I can get them merged in (added some new blocks in 1.19)

**Comment by DancerVlt69** [comment]
Me and PR? This was my first one! I've had to learn it first how it works! ;)

For the de - Localization | done

For the Tag-Files first I will compare my older files with your latest one.

**Comment by DancerVlt69** [comment]
Btw, the new dried Items and Blocks looking fantastic!
