### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by Telezhka-the-First** [nanite/Bamboo-Everything#38]
### Feature Description

Well, it's all in the title. Here I give you a ru_ru.json file content to add it.

{
  "itemGroup.bambooeverything.bambooeverything": "Bamboo Everything",
  "block.bambooeverything.bamboo_ladder": "Бамбуковая лестница",
  "block.bambooeverything.bamboo_fence": "Бамбуковый забор",
  "block.bambooeverything.bamboo_fence_gate": "Бамбуковая калитка",
  "block.bambooeverything.bamboo_door": "Бамбуковая дверь",
  "block.bambooeverything.bamboo_trapdoor": "Бамбуковый люк",
  "block.bambooeverything.bamboo_bundle": "Блок бамбука",
  "block.bambooeverything.bamboo_stairs": "Бамбуковые ступеньки",
  "block.bambooeverything.bamboo_slab": "Бамбуковая плита",
  "item.bambooeverything.bamboo_raft": "Бамбуковый плот"
}

**Comment by Telezhka-the-First** [comment]
It's not actually completed: there's no Russian language in the mod, and my pull request still not merged. Why did you close it as completed?

**Comment by Gaz492** [comment]
Apologies, I selected all issues and closed them in bulk, ill take a look at the PR when im free next!
