### ISSUE TITLE
Crash Report - Fabric 0.6.3+build.167 on 1.14.4

### ISSUE THREAD

**Issue by Iamthedogev** [nanite/Bamboo-Everything#4]
https://paste.ee/p/4pZQ5

I'm unsure what mod is causing the issue here - while making a personal modpack, I singled out that using Bamboo Everything (https://www.curseforge.com/minecraft/mc-mods/bamboo-everything-fabric) and Buffer (https://www.curseforge.com/minecraft/mc-mods/buffer) together was causing the game to crash on launch. I have made this report on both mods in the hope to find a solution.

**Comment by vini2003** [comment]
https://github.com/vini2003/Buffer/issues/4
