### ISSUE TITLE
[1.18]

### ISSUE THREAD

**Issue by C0D3-M4513R** [nanite/Bamboo-Everything#51]
### Minecraft Version

1.18.2

### Modloader

forge 40.2.4

### Mod version

forge-1.3.3-build.34

### Repeatable?

- [X] Yes

### Link to log files

`[06Jun2023 22:33:07.236] [Worker-Main-6/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag minecraft:boats as it is missing following references: bambooeverything:dry_bamboo_raft (from BambooEverything-forge-1.3.3-build.34+mc1.18.2.jar)`
https://cdn.discordapp.com/attachments/1115741811235901462/1115742155152052314/latest_3.7z

### Steps to reproduce the issue

1. use bamboo everything

### Description of the issue you are having

Bambooeverything does not register items correctly and causes errors with magma and worldguard.

https://mclo.gs/5trRNuE

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
It looks like you have an outdated version of the mod, I believe that this issue has already been fixed.
The latest version of the mod can be found at https://www.curseforge.com/minecraft/mc-mods/bamboo-everything/files/4359591

**Comment by C0D3-M4513R** [comment]
Is the fix backwardscompatible?
I'm using all the mods 7, and can't just upgrade/downgrade versions freely.

**Comment by Gaz492** [comment]
Probably not as the versions between server and client will be different, you will need to go poke the ATM7 developers to get the mod updated.

**Comment by C0D3-M4513R** [comment]
time to privately build https://github.com/nanite/Bamboo-Everything/commit/80ebba846ed266e3934e61f758974ab83eccdced
