### ISSUE TITLE
[1.21] Mod incompatibility with NeoForge 

### ISSUE THREAD

**Issue by Periam** [nanite/Bamboo-Everything#55]
### Minecraft Version

1.21

### Modloader

Neoforge 21.0.14

### Mod version

BambooEverything-neoforge-21.0.0+mc1.21

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/user-attachments/files/15875489/latest.log)

### Steps to reproduce the issue

Install the mod and start the game.

### Description of the issue you are having

After installing the mod and the launch screen start making normal checks the game crash

![Screenshot 2024-06-17 153306](https://github.com/nanite/Bamboo-Everything/assets/13920185/d454c2e3-0427-4d87-bc2e-832bb70662b5)

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
Fixed version should be available on curseforge now.
