### ISSUE TITLE
feature suggestion :)

### ISSUE THREAD

**Issue by maddikarp** [nanite/Bamboo-Everything#7]
Love the pack, btw! I was wondering if you would consider making all of the same items with a dried bamboo texture? For reference, the color palette of the scaffolds. In real life architecture dried bamboo is used a lot, and I would love to build using that!

**Comment by Gaz492** [comment]
Its something I can probably get around to do and also think it will look great. 
Thank you for your suggestion.

**Comment by maddikarp** [comment]
Awesome!! Thank you, too!

**Comment by Gaz492** [comment]
Added
